apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      template:
    metadata:
      labels:
        app: backend
        spec:
      containers:
      - name: backend-python
        image: mamoon123/python-backend:v1.1
        ports:
        - containerPort: 8080
          name: tcp
        resources:
          limits:
            cpu: 500m
        #assign resources are 200m
          requests:
            cpu: 200m

---
# if type not specified by default it would be clusterip
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    
ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
